//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimmingPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        public int SheduleID { get; set; }
        public int IDPool { get; set; }
        public int IDEmployee { get; set; }
        public int IDSales { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string DayOfWek { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Pools Pools { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
